from Solver import *
import time
from datetime import timedelta

# t = time.perf_counter()
# Day1.Part1()
# print(f"Duration: {time.perf_counter()-t:0.4f} s\n")

# t = time.perf_counter()
# Day1.Part2()
# print(f"Duration: {time.perf_counter()-t:0.4f} s\n")

# t = time.perf_counter()
# Day2.Part1()
# print(f"Duration: {time.perf_counter()-t:0.4f} s\n")
# t = time.perf_counter()
# Day2.Part2()
# print(f"Duration: {time.perf_counter()-t:0.4f} s\n")

# t = time.perf_counter()
# Day3.Part1()
# print(f"Duration: {time.perf_counter()-t:0.4f} s\n")
# t = time.perf_counter()
# Day3.Part2()
# print(f"Duration: {time.perf_counter()-t:0.4f} s\n")

# t = time.perf_counter()
# Day4.Part1()
# print(f"Duration: {time.perf_counter()-t:0.4f} s\n")
# t = time.perf_counter()
# Day4.Part2()
# print(f"Duration: {time.perf_counter()-t:0.4f} s\n")

# t = time.perf_counter()
# Day5.Part1()
# print(f"Duration: {time.perf_counter()-t:0.4f} s\n")
# t = time.perf_counter()
# Day5.Part2()
# print(f"Duration: {time.perf_counter()-t:0.4f} s\n")

# t = time.perf_counter()
# Day6.Part1()
# print(f"Duration: {time.perf_counter()-t:0.4f} s\n")
# t = time.perf_counter()
# Day6.Part2()
# print(f"Duration: {time.perf_counter()-t:0.4f} s\n")

# t = time.perf_counter()
# Day7.Part1()
# print(f"Duration: {time.perf_counter()-t:0.4f} s\n")
# t = time.perf_counter()
# Day7.Part2()
# print(f"Duration: {time.perf_counter()-t:0.4f} s\n")

# t = time.perf_counter()
# Day8.Part1()
# print(f"Duration: {time.perf_counter()-t:0.4f} s\n")
# t = time.perf_counter()
# Day8.Part2()
# print(f"Duration: {time.perf_counter()-t:0.4f} s\n")

# t = time.perf_counter()
# Day9.Part1()
# print(f"Duration: {time.perf_counter()-t:0.4f} s\n")
# t = time.perf_counter()
# Day9.Part2()
# print(f"Duration: {time.perf_counter()-t:0.4f} s\n")

# t = time.perf_counter()
# Day10.Part1()
# print(f"Duration: {time.perf_counter()-t:0.4f} s\n")
# t = time.perf_counter()
# Day10.Part2()
# print(f"Duration: {time.perf_counter()-t:0.4f} s\n")

# t = time.perf_counter()
# Day11.Part1()
# print(f"Duration: {time.perf_counter()-t:0.4f} s\n")
# t = time.perf_counter()
# Day11.Part2()
# print(f"Duration: {time.perf_counter()-t:0.4f} s\n")

# t = time.perf_counter()
# Day12.Part1()
# print(f"Duration: {time.perf_counter()-t:0.4f} s\n")
# t = time.perf_counter()
# Day12.Part2()
# print(f"Duration: {time.perf_counter()-t:0.4f} s\n")

t = time.perf_counter()
Day13.Part1()
print(f"Duration: {time.perf_counter()-t:0.4f} s\n")
t = time.perf_counter()
Day13.Part2()
print(f"Duration: {time.perf_counter()-t:0.4f} s\n")

print("THE END!")